# Generated by Django 2.2.16 on 2022-01-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220112_2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
